transform doctest to python-test skip in Zope4 due to crazy test-isolation-issues with newest zope.testrunner
Running it leads to:
  File "/Users/philip/workspace/coredev/src/plone.supermodel/plone/supermodel/model.py", line 87, in walk
    for child in schema.dependents.keys():
ConfigurationExecutionError: <type 'exceptions.AttributeError'>: 'VerifyingAdapterLookup' object has no attribute 'dependents'
  in:
  File "/Users/philip/workspace/coredev/src/plone.supermodel/plone/supermodel/configure.zcml", line 9.4-12.10
      <zcml:customAction
          handler=".model.finalizeSchemas"
          order="9999999"
          />